version: '2.2'
services:
  clasp:
    working_dir: /root
    env_file: .env
    build:
      context: .
    volumes:
      - $PWD:/root:delegated
    entrypoint: clasp
  initialize-clasp:
    extends: clasp
    entrypoint: sh -c scripts/initialize_clasp.sh
  get-script-id:
    extends: clasp
    entrypoint: sh scripts/get_script_id.sh
  login:
    extends: clasp
    command:
      - login
      - --creds
      - creds.json
      - --no-localhost
  create:
    extends: clasp
    command:
      - create
      - --title
      - "Expensify Integrations"
      - --parentId
      - "${GOOGLE_SHEET_ID_TO_USE}"
  pull:
    extends: clasp
    command:
      - pull
  push:
    extends: clasp
    command:
      - push
  run:
    extends: clasp
    command:
      - run
  push:
    extends: clasp
    command:
      - push
  deploy:
    extends: clasp
    command:
      - deploy
  configure:
    extends: clasp
    entrypoint: sh
    command:
      - "scripts/configure"
  tests:
    extends: clasp
    entrypoint: bats
    command:
      - 'tests/'
