version: '2.2'
services:
  clasp:
    working_dir: /root
    env_file: .env
    build:
      context: .
    volumes:
      - $PWD:/root:delegated
    entrypoint: clasp
  login:
    extends: clasp
    command:
      - login
      - --creds
      - creds.json
      - --no-localhost
  create:
    extends: clasp
    command:
      - create
      - --title
      - "Expensify Integrations"
      - --parentId
      - "${GOOGLE_SHEET_ID_TO_USE}"
  pull:
    extends: clasp
    command:
      - pull
  run:
    extends: clasp
    command:
      - run
  deploy:
    extends: clasp
    entrypoint: sh
    command:
      - -c
      - "Run scripts/deploy.sh instead; add --help for options."
  execute:
    extends: clasp
    entrypoint: sh
    command:
      - -c
      - "Run scripts/execute.sh instead; add --help for options."
  tests:
    extends: clasp
    entrypoint: bats
    command:
      - 'tests/'
